GhalibResearch/ViewModels/SentArticleListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GhalibResearch.ViewModels
{
    public class SentArticleListViewModel
    {
        public int SentArticleId { get; set; }
        public string ArticleTitle { get; set; }
        public string OrganizationName { get; set; }
        public int CopiesCount { get; set; }
        public DateTime SentDate { get; set; }
        public string SentDateString { get; set; }

    }
}

GhalibResearch/Controllers/SentArticleController.cs
using Dapper;
using GhalibResearch.Models;
using GhalibResearch.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using ShamisDateTime;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using static GhalibResearch.DataAccess.ZTable;

namespace GhalibResearch.Controllers
{
    public class SentArticleController : Controller
    {
     
        public IActionResult Index()
        {
            var model = new AddOrEditSentArticleViewModel { };
            using SqlConnection sql = new(Startup.ConnectionString);
            model.Organization = sql.Query<OrganizationModel>("GetOrganizationList", commandType: CommandType.StoredProcedure);
            model.Article = Article.GetAll().Select(a => new SelectListItem
            {
                Value = a.ArticleId.ToString(),
                Text = a.ArticleTitle.ToString()
            });
            return View(model);
        }
   
        public IActionResult AddSentArticle([FromBody] IEnumerable<SentArticleModel> model)
        {
            DynamicParameters param = new();

            using SqlConnection sql = new(Startup.ConnectionString);
            foreach (var item in model)
            {
                param.Add("OrganizationId", item.OrganizationId);
                param.Add("ArticleId", item.ArticleId);
                item.SentDate = PersianDateTime.Parse(item.SentDateString).ToDateTime();
                param.Add("SentDate", item.SentDate);
                param.Add("CopiesCount", item.CopiesCount);
                param.Add("UserName", User.Identity.Name);

                sql.Query("AddSentArticle", param, commandType: CommandType.StoredProcedure);
            }
            return Json("موفقانه ثبت شد");
        }

        public IActionResult SentArticleList()
        {
            var model = new AddOrEditSentArticleViewModel() { };
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            model.SentArticleList = sql.Query<SentArticleListViewModel>("GetSentArticleList", commandType: CommandType.StoredProcedure);

            return View(model);
        }

        public IActionResult DeleteSentArticle(int id)
        {
            var template = new
            {
                SentArticleId = id
            };
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            sql.Query("DeleteSentArticle", template,commandType: CommandType.StoredProcedure);

            return RedirectToAction("SentArticleList");
        }

        public IActionResult EditSentArticle(int id)
        {
            var template = new
            {
                SentArticleId = id
            };
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            var model = new AddOrEditSentArticleViewModel()
            {
                SentArticle = sql.QuerySingle<SentArticleModel>("SelectSentArticleToEdit", template, commandType: CommandType.StoredProcedure)
            };
            model.Article = Article.GetAll().Select(a => new SelectListItem
            {
                Value = a.ArticleId.ToString(),
                Text = a.ArticleTitle.ToString(),
                Selected =a.ArticleId==model.SentArticle.ArticleId
            });

            return View(model);
        }

     
        public IActionResult EditSentArticlePost([FromBody] IEnumerable<SentArticleModel> model)
        {
            DynamicParameters param = new DynamicParameters();
            foreach (var item in model)
            {

                param.Add("SentArticleId", item.SentArticleId);
                param.Add("ArticleId", item.ArticleId);
                item.SentDate = PersianDateTime.Parse(item.SentDateString).ToDateTime();
                param.Add("SentDate", item.SentDate);
                param.Add("CopiesCount", item.CopiesCount);


                using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
                sql.Query("EditSentArticle", param, commandType: CommandType.StoredProcedure);
            }
            return RedirectToAction("Index");
           
        }
    }
}

GhalibResearch/Views/SentArticle/EditSentArticle.cshtml
@model AddOrEditSentArticleViewModel

<div class="row mg-b-5">
    <div class="col-lg-3">
        <div class="form-group">
            <label class="form-control-label float-right">سازمان</label>
            <input class="form-control" type="text" disabled value="@Model.SentArticle.OrganizationName" autocomplete="off">
        </div>

    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label class="form-control-label float-right">مقاله</label>
            <select class="form-control select2 " asp-items="Model.Article" id="ArticleId" name="ArticleId" tabindex="1" aria-hidden="true">
                <option label="انتخاب مقاله"></option>
            </select>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label class="form-control-label float-right">تاریخ ارسال</label>
            <input class="form-control shamsi-date-picker" type="text" value="@(new ShamisDateTime.PersianDateTime(Model.SentArticle.SentDate).ToShortDateString())" name="SentDateString" id="SentDateString" autocomplete="off">
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <label class="form-control-label float-right">تعداد کاپی</label>
            <input class="form-control" type="text" value="@Model.SentArticle.CopiesCount" name="CopiesCount" id="CopiesCount" autocomplete="off">
        </div>
    </div>
</div>
<input type="hidden" id="SentArticleId" value="@Model.SentArticle.SentArticleId" />
<div class="row mg-b-5">
    <div class="col-lg-3">
        <button id="btnSubmit" class="btn btn-primary float-right">ثبت</button>
        <a class="btn btn-secondary float-right" href="~/SentArticle/SentArticleList" >لغو</a>
    </div>
</div>

@section scripts{
    <script src="~/plugins/shamsidatepicker/datepicker.min.js"></script>
    <script>

        $(document).ready(function () {
            $("input.shamsi-date-picker").persianDatepicker({ showGregorianDate: !1 });

            $("button#btnSubmit").click(function () {
                var checkedList = [];

                var o = {
                    SentArticleId: $("#SentArticleId").val(),
                    ArticleId: $("#ArticleId").val(),
                    SentDateString: $("#SentDateString").val(),
                    CopiesCount: $("#CopiesCount").val()
                };
                checkedList.push(o);

                $.ajax({
                url: "@Url.Action("EditSentArticlePost", "SentArticle")",
                type: "POST",
                cache: false,
                contentType: "application/json;charset=utf-8",
                dataType: "html",
                data: JSON.stringify(checkedList),
                    success: function (data) {

                           @* @Url.Action("Index","SentArticle");*@
                             location.href = '@Url.Action("SentArticleList", "SentArticle")'
                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });

            });

        });
    </script>
}

GhalibResearch/Views/SentArticle/Index.cshtml
@model AddOrEditSentArticleViewModel

<div class="row">

    <div class="col-md-4">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label class="form-control-label float-right">مقاله</label>
                    <select class="form-control select2 " asp-items="Model.Article" id="ArticleId" name="ArticleId" tabindex="1" aria-hidden="true">
                        <option label="انتخاب مقاله"></option>
                    </select>
                </div>
            </div>
        </div><!-- row -->
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label class="form-control-label float-right">تاریخ ارسال</label>
                    <input class="form-control shamsi-date-picker" type="text" name="SentDateString" id="SentDateString" autocomplete="off">
                </div>
            </div>
        </div><!-- row -->
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label class="form-control-label float-right">تعداد کاپی</label>
                    <input class="form-control" type="text" name="CopiesCount" id="CopiesCount" autocomplete="off">
                </div>
            </div>
        </div><!-- row -->
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <button id="btnSubmit" class="btn-primary btn-block mg-b-10">ثبت</button>
                </div>
            </div>
        </div><!-- row -->

    </div><!-- col-3 -->

    <div class="col-md-8 overflow-auto">
        <table id="datatable1" class="table display responsive nowrap">
            <thead>
                <tr>
                    <th>شماره</th>
                    <th><input type="checkbox" id="selectAll" /></th>
                    <th>نام اداره</th>
                </tr>
            </thead>
            <tbody>
                @{int row = 1;
                }
                @foreach (var temp in Model.Organization)
                {
                    <tr>
                        <td>@row</td>
                        <td>
                            <input type="checkbox" />
                            <input type="hidden" name="OrganizationId" value="@temp.OrganizationId" class="" />
                        </td>
                        <td>@temp.OrganizationName</td>
                    </tr>

                    row++;
                }
            </tbody>
        </table>
    </div><!-- col-9 -->
</div>

@section scripts{
    <script src="~/plugins/shamsidatepicker/datepicker.min.js"></script>
    <script>

        $(document).ready(function () {
            $('#datatable1').DataTable({
                responsive: true,
                language: {
                    searchPlaceholder: 'جستجو ...',
                    sSearch: '',
                    lengthMenu: '_MENU_ نام اداره در یک صفحه',
                }
            });

            $("input.shamsi-date-picker").persianDatepicker({ showGregorianDate: !1 });

            $("#selectAll").click(function () {
                $("input[type=checkbox]").prop('checked', $(this).prop('checked'));

            });

            $("button#btnSubmit").click(function () {
                var checkedList = [];

                $("#datatable1 tbody tr").each(function () {
                    if ($(this).find("input:checkbox").is(':checked')) {
                        var o = {
                            OrganizationId: $(this).find("input:hidden").val(),
                            ArticleId: $("#ArticleId").val(),
                            SentDateString: $("#SentDateString").val(),
                            CopiesCount: $("#CopiesCount").val()
                        };
                        checkedList.push(o);
                    }
                });

                $.ajax({
                    url: "@Url.Action("AddSentArticle", "SentArticle")",
                    type: "POST",
                    cache: false,
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    data: JSON.stringify(checkedList),
                    success: function (data) {
                        alert(data);
                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });

            });

        });
    </script>
}

GhalibResearch/Views/SentArticle/SentArticleList.cshtml
@model AddOrEditSentArticleViewModel


<div class="section-wrapper">
    <div class="table-wrapper">
        <div id="datatable1_wrapper" class="dataTables_wrapper no-footer">
            <div id="datatable1_wrapper" class="dataTables_wrapper no-footer">

            </div><table id="datatable1" class="table display responsive nowrap dataTable no-footer dtr-inline" role="grid" aria-describedby="datatable1_info" style="width: 1032px;">

                <thead>
                    <tr role="row">
                        <th class="wd-15p sorting">شماره</th>
                        <th class="wd-15p sorting">عنوان مقاله</th>
                        <th class="wd-15p sorting">سازمان</th>
                        <th class="wd-15p sorting">تعداد کاپی</th>
                        <th class="wd-20p sorting">تاریخ ارسال</th>
                        <th class="wd-20p sorting">عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    @{int num = 1; }
                    @foreach (var temp in Model.SentArticleList)
                    {
                        <tr role="row" class="even">
                            <td>@num</td>
                            <td>@temp.ArticleTitle</td>
                            <td>@temp.OrganizationName</td>
                            <td>@temp.CopiesCount</td>
                            <td>@(new ShamisDateTime.PersianDateTime(temp.SentDate).ToShortDateString())</td>
                            <td>
                                <a asp-action="DeleteSentArticle" asp-route-id="@temp.SentArticleId" onclick="return confirm('Are you sure?')"><i class="icon ion-trash-a font-16"></i></a>
                                <a asp-action="EditSentArticle" asp-route-id="@temp.SentArticleId" class="mr-2"><i class="icon ion-edit font-16"></i></a>
                            </td>
                        </tr>
                        num++;
                    }
                </tbody>
            </table>
        </div>
    </div><!-- table-wrapper -->
</div>

@section scripts{

    <script>
        $(function () {
            'use strict';

            $('#datatable1').DataTable({
                responsive: true,
                language: {
                    searchPlaceholder: 'Search...',
                    sSearch: '',
                    lengthMenu: '_MENU_ مقاله در یک صفحه',
                }
            });

            $('#datatable2').DataTable({
                bLengthChange: false,
                searching: false,
                responsive: true
            });

            // Select2
            $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        });
    </script>

}