GhalibResearch/Controllers/OrganizationController.cs
using Dapper;
using GhalibResearch.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace GhalibResearch.Controllers
{
   // [Authorize]
    public class OrganizationController : Controller
    {

        [HttpGet]
        public IActionResult Add()
        {
            var model = new AddOrEditOrganizationViewModel() { };
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            model.OrganizationList = sql.Query<OrganizationModel>("GetOrganizationList", commandType: CommandType.StoredProcedure);
           

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Add(OrganizationModel model)
        {
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            if (ModelState.IsValid)
            {

                var template = new
                {
                    model.OrganizationName
                };

                DynamicParameters parameters = new DynamicParameters(template);


                await sql.QueryAsync("AddOrganization", parameters, commandType: CommandType.StoredProcedure);
            }


            var ViewModel = new AddOrEditOrganizationViewModel() { };
            ViewModel.AddModel = model;
            ViewModel.OrganizationList = sql.Query<OrganizationModel>("GetOrganizationList", commandType: CommandType.StoredProcedure);


            return View(ViewModel);

        }

        [HttpGet]
        public IActionResult DeleteOrganization(int id) {
            var template = new {
                OrganizationId = id
            };
            DynamicParameters param = new DynamicParameters(template);

            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            sql.Query("DeleteOrganization", param, commandType: CommandType.StoredProcedure);
            return RedirectToAction("Add");
        }


        public IActionResult EditOrganization(int id)
        {
            var template = new
            {
                OrganizationId = id
            };
            var ViewModel = new AddOrEditOrganizationViewModel() { };

            DynamicParameters param = new DynamicParameters(template);
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);

            ViewModel.EditModel=sql.QuerySingle<OrganizationModel>("SelectOrganizationToEdit", param, commandType: CommandType.StoredProcedure);
            ViewModel.OrganizationList = sql.Query<OrganizationModel>("GetOrganizationList", commandType: CommandType.StoredProcedure);




            return View(nameof(Add), ViewModel);

        }

        [HttpPost]
        public IActionResult EditOrganization(OrganizationModel model)
        {
            var template = new
            {
                model.OrganizationId,
                model.OrganizationName

            };

            DynamicParameters param = new DynamicParameters(template);
            using SqlConnection sql = new SqlConnection(Startup.ConnectionString);
            sql.Query("EditOrganization",param,commandType: CommandType.StoredProcedure);

            return RedirectToAction("Add");
        }

    }
}

GhalibResearch/Views/Organization/Add.cshtml
@model AddOrEditOrganizationViewModel

@{
    Layout = "_Layout";
}

@if (Model.EditModel != null)
{
    <div class="row">
        <div class="col-md-12">
            <form method="post" asp-controller="Organization" asp-action="EditOrganization">
                <input type="hidden" value="@Model.EditModel.OrganizationId" name="OrganizationId" />
                <div class="form-layout">
                    <div class="form-group">
                        <label class="form-control-label float-right">نام سازمان</label>
                        <input class="form-control" type="text" name="OrganizationName" value="@Model.EditModel.OrganizationName" placeholder="Type here...">
                        
                    </div>

                    <div class="form-layout-footer">
                        <button class="btn btn-primary bd-0 float-lg-right" type="submit"> <i class="fa fa-edit"></i> ویرایش نام </button>
                        <a class="btn btn-secondary bd-0 float-lg-right" asp-action="Add" asp-controller="Organization"> <i class="fa fa-backward"></i> انصراف </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <form method="post" asp-controller="Organization" asp-action="Add" novalidate>
                <div class="form-layout">
                    <div class="form-group">
                        <label  asp-for="@Model.AddModel.OrganizationName" class="form-control-label float-right">نام سازمان</label>
                        <input class="form-control" type="text" asp-for="@Model.AddModel.OrganizationName" name="OrganizationName" placeholder="...اینجا بنویسید">
                        <span asp-validation-for="@Model.AddModel.OrganizationName" class="danger"></span>
                    </div>

                    <div class="form-layout-footer">
                        <button class="btn btn-primary bd-0 float-lg-right" type="submit"> <i class="fa fa-plus-circle"></i> افزودن سازمان </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
}

<div class="row mt-5">
    <div class="col-md-12">
        <table id="datatable1" class="table display responsive nowrap">
            <thead>
                <tr>
                    <th class="wd-5p">شماره</th>
                    <th>نام سازمان</th>
                    <th class="wd-5p">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @{int counter = 0; }
                @foreach (var item in Model.OrganizationList)
                {
                    counter++;
                    <tr role="row" class="even">

                        <td class="text-right">@counter</td>
                        <td class="text-right">@item.OrganizationName</td>
                        <td class="text-right">
                            <a asp-action="DeleteOrganization" asp-route-id="@item.OrganizationId" onclick="return confirm('Are you sure?')"><i class="fa fa-times"></i></a>
                            <a asp-action="EditOrganization" asp-route-id="@item.OrganizationId" class="mr-2"><i class="fa fa-edit"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script>
        $(function () {
            $('#datatable1').DataTable({
                responsive: true,
                language: {
                    searchPlaceholder: 'جستجو ...',
                    sSearch: '',
                    lengthMenu: '_MENU_ مقاله در یک صفحه',
                }
            });
        });
    </script>
}

GhalibResearch/Views/Organization/_EditOrganization.cshtml
@model AddOrEditOrganizationViewModel

<div class="row">
    <div class="col-md-12">
        <form method="post" asp-controller="Organization" asp-action="EditOrganization" novalidate>
            <div class="form-layout">
                <div class="row mg-b-25">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <input type="hidden" value="@Model.EditModel.OrganizationId" name="OrganizationId" />
                            <label class="form-control-label float-right">نام سازمان</label>
                            <input class="form-control" type="text" name="OrganizationName" value="@Model.EditModel.OrganizationName" placeholder="Type here...">
                            @*<span class="tx-danger" asp-validation-for="organization.OrganizationName"></span>*@
                        </div>
                    </div><!-- col-4 -->

                </div><!-- row -->

                <div class="form-layout-footer">
                    <button class="btn btn-primary bd-0 float-lg-right" type="submit">ثبت</button>
                    <a class="btn btn-secondary bd-0 float-lg-right" href="~/Organization/Add" >لغو</a>
                </div><!-- form-layout-footer -->
            </div>
        </form>
    </div>
    <!-- Organization Table -->

</div>